package db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import db.bean.LocalPPT;
import db.bean.SbumitVoice;

import db.dao.LocalPPTDao;
import db.dao.SbumitVoiceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localPPTDaoConfig;
    private final DaoConfig sbumitVoiceDaoConfig;

    private final LocalPPTDao localPPTDao;
    private final SbumitVoiceDao sbumitVoiceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localPPTDaoConfig = daoConfigMap.get(LocalPPTDao.class).clone();
        localPPTDaoConfig.initIdentityScope(type);

        sbumitVoiceDaoConfig = daoConfigMap.get(SbumitVoiceDao.class).clone();
        sbumitVoiceDaoConfig.initIdentityScope(type);

        localPPTDao = new LocalPPTDao(localPPTDaoConfig, this);
        sbumitVoiceDao = new SbumitVoiceDao(sbumitVoiceDaoConfig, this);

        registerDao(LocalPPT.class, localPPTDao);
        registerDao(SbumitVoice.class, sbumitVoiceDao);
    }
    
    public void clear() {
        localPPTDaoConfig.getIdentityScope().clear();
        sbumitVoiceDaoConfig.getIdentityScope().clear();
    }

    public LocalPPTDao getLocalPPTDao() {
        return localPPTDao;
    }

    public SbumitVoiceDao getSbumitVoiceDao() {
        return sbumitVoiceDao;
    }

}
