package db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCAL_PPT".
 */
public class LocalPPT {

    private Long id;
    private String title;
    private String path;
    private String status;
    private String time;

    public LocalPPT() {
    }

    public LocalPPT(Long id) {
        this.id = id;
    }

    public LocalPPT(Long id, String title, String path, String status, String time) {
        this.id = id;
        this.title = title;
        this.path = path;
        this.status = status;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
