package db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SBUMIT_VOICE".
 */
public class SbumitVoice {

    private Long id;
    private String nid;
    private String title;
    private String path;

    public SbumitVoice() {
    }

    public SbumitVoice(Long id) {
        this.id = id;
    }

    public SbumitVoice(Long id, String nid, String title, String path) {
        this.id = id;
        this.nid = nid;
        this.title = title;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNid() {
        return nid;
    }

    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
